### PR TITLE
Fix old maps where OD defines both AR & OD

### PR DESCRIPTION
**Pull request by Tibowl**
Example map: https://osu.ppy.sh/s/4651

### CODE REVIEW

**Comment by derekxwu** [comment]
Good catch, I forgot about those.

Because of how the parsing works, this fix will put `'OverallDifficulty: 8.3'` (for example) in `bm_info['AR']`. You'll either want to slice the number and add it to `'ApproachRate:'` **or** ignore `bm_info['AR']` in the rest of the code, as oppai itself works for maps without AR.

As a tangent, since AR doesn't factor into difficulty calculation, need we parse it at all?

**Comment by Tibowl** [comment]
Why do we actually need to parse anything? We can just let oppai handle everything and remove the parse section and use this:

``` python
    metadata, hitcircles = read(bmap)
    bm_head = ''.join(metadata) + '[HitObjects]\r\n'
```

**Comment by derekxwu** [comment]
The thought at the time was to reduce IO overhead, since oppai-chunks works by writing to temp files and running oppai on them. Something to benchmark, I guess.

**Comment by derekxwu** [comment]
Using `The Unforgiving [Marathon]` as a test map, parsing and stripping takes 26.4s and just copying the first half takes 31.5s. I'll leave it as-is.

**Pull request closed without merging**
